### ISSUE TITLE
"utf-8" is not a supported encoding name

### ISSUE THREAD

**Issue by andy61i** [skazantsev/WebDavClient#1]
WebDAV at Synology DS 215+ (DSM 5.2-5644 Update 1).

WebDavClient.Propfind("file name") throws an exception:

{"The character set provided in ContentType is invalid. Cannot read content as string using an invalid character set."}	System.Exception {System.InvalidOperationException}

InnerException	{"'\"utf-8\"' is not a supported encoding name.\r\nParameter name: name"}	System.Exception {System.ArgumentException}

StackTrace:
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
at WebDav.WebDavClient.<Propfind>d__2.MoveNext()

**Comment by andy61i** [comment]
Here is my code (embedded into WebDav.ClientConsole):

        private static void AndyTest()
        {
            WebDavClientParams clientParams = new WebDavClientParams()
            {
                BaseAddress = new Uri("http://192.168.1.90:5005/home/"),
                Credentials = new NetworkCredential("andy", "PASSWORD"),
                UseDefaultCredentials = false
            };            
            using (var client = new WebDavClient(clientParams))
            {
                try
                {
                    PropfindResponse res = client.Propfind("SafeInCloud.db").Result;
                    Debug.WriteLine(res.ToString());
                }
                catch (Exception ex)
                {
                    Debug.WriteLine(ex.ToString());
                }
            }
        }

**Comment by andy61i** [comment]
BTW. This lib works just fine with my setup: https://github.com/saguiitay/WebDAVClient

**Comment by andy61i** [comment]
Clue: https://connect.microsoft.com/VisualStudio/feedback/details/790174/system-net-http-httpcontent-readasstringasync-does-not-handle-imperfect-content-type-headers

**Comment by skazantsev** [comment]
@andy61i Thank you for bringing this up.
I've made a workaround in code for this bug in HttpClient - https://github.com/skazantsev/WebDavClient/commit/e7b245700382639634e8349354e6c4a1bc3ea3cc 
A new version of the package is available in nuget.
