### ISSUE TITLE
Connection to owncloud fails

### ISSUE THREAD

**Issue by PeterHagen** [skazantsev/WebDavClient#10]
I run a apache webserver, which has an OwnCloud instance running. I also host some docker instances, and one uses WebDavClient to send files to OwnCloud. For this I have a few unit test that test uploading a file and creating directories. When I run this locally from Visual Studio 2017, it makes a connection to my server and all tests are ok.

A short while ago, I ported all my code to .Net Core 2.0. I tried to deploy my site as the docker instance, and while building the code it also runs the test again. And they fail. So, my first thought was that from Docker, the test couldn't connect to my host webserver, or maybe something with https issues (but actually, before going to 2.0 it also worked). I therefor added a manual httpClient call to the same webdav url, with basic authentication. And this tests works. 

I monitored the apache logs of owncloud, and what I noticed, that every time my local unit test starts, there is a request with a 407 message, and second a 207 request with my username in it:

```
31.x.x.x - - [06/Sep/2017:11:23:03 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 401 306 "-" "-"
31.x.x.x - peter [06/Sep/2017:11:23:04 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 2021 "-" "-"
```
But when I run the docker unit test, only the first one occurs. I checked the code, but can't seem to find why and how the 2 calls are made, and why in Docker only the first occurs.

I did find a solution. By added a manual header with the basic authentication to the client parameters, my problem is resolved. But, how does this work? Is this a feature of HttpClient to detect the authentication request and add the credentials? Is it possible to override this behaviour from the code. I did try the PreAuthenticate setting, but it doesn't seem to affect anything.

**Comment by skazantsev** [comment]
Hi Peter,

I think this is a standard behavior of HttpClient, see [Why would HTTP client only send authentication headers once an unauthenticated request was rejected?](https://security.stackexchange.com/questions/67105/why-would-http-client-only-send-authentication-headers-once-an-unauthenticated-r).

The PreAuthenticate property only tells HttpClient to set the Authorization header after the first request. See [HttpClientHandler.PreAuthenticate Property](https://msdn.microsoft.com/en-us/library/system.net.http.httpclienthandler.preauthenticate(v=vs.110).aspx).
```
With the exception of the first request, the PreAuthenticate property indicates whether to send authentication information with subsequent requests to a Uri that matches the specific Uri up to the last forward slash without waiting to be challenged by the server.
```

I don't know why the standard challenge-response authentication doesn't work in your case but the workaround with setting the Authentication header explicitly is the only way to avoid a challenge response from the server.

Regards,
Sergey
