### ISSUE TITLE
UseDefaultCredentials not being set to false when Credentials supplied

### ISSUE THREAD

**Issue by drbergeron** [skazantsev/WebDavClient#13]
issue is with ConfigureHttpClient method in WebDavClient.cs.

Consider the following code:
```
 _clientParams = new WebDavClientParams()
            {
                BaseAddress = new Uri(url),
                Credentials = new NetworkCredential() { UserName = "test", Password = "test" },
                UseDefaultCredentials = false
            };
using (var webDavClient = new WebDavClient(_clientParams))
            {
                var result = await webDavClient.Propfind(_fileToGet);
                if (result.IsSuccessful){}
                // continue ...
                else{}
                // handle an error

                return "";
            }
```

Even though i'm explicitly setting credentials, i must also set UseDefaultCredentials to false for it to auth correctly. If you update this code to remove UseDefaultCredentials=false, you'll get a 403 when trying to .Propfind 

I have a branch with fix already, or make the following change to ConfigureHttpClient:
```
if (@params.Credentials != null)
            {
                httpHandler.Credentials = @params.Credentials;
                httpHandler.UseDefaultCredentials = false;
            }
```

This is also likely the cause of the other issue reported.

**Comment by skazantsev** [comment]
Hi @drbergeron,
I confirm the problem and think the proposed change makes sense.
I'll apply your fix and release a new version.
Thank you for bringing this up!
