### ISSUE TITLE
Download a file locally.

### ISSUE THREAD

**Issue by SissiKonsta** [skazantsev/WebDavClient#16]
Hello, 

I'm trying to download a file locally using WebDAC.Client. The file is being created but it is empty. Any ideas how to solve this?

Thanks.

**Comment by skazantsev** [comment]
Hi @SissiKonsta,

What version of a library do you use? Could you post a code snippet that indicates the issue?

**Comment by skazantsev** [comment]
This bug does not have sufficient details to investigate. I will close it for now. Feel free to re-open it if the details are provided.
