### ISSUE TITLE
[Question] PutFile returns 204 No Content when a file is overwritten

### ISSUE THREAD

**Issue by EHekkert** [skazantsev/WebDavClient#34]
PutFile incorrectly reports that the file has no content when overwriting an already existing file.

**Comment by EHekkert** [comment]
var clientParams = new WebDavClientParams
{
    BaseAddress = new Uri(outputFileUri),
    Credentials = new NetworkCredential(outputFileUriUser, outputFileUriPassword)
};
IWebDavClient client = new WebDavClient(clientParams);

// move generated file to output uri
WebDavResponse response = client.PutFile(outputFileName, File.OpenRead(tempFile)).Result;

**Comment by skazantsev** [comment]
I'll keep this issue open with a question label .

Most of WebDAV servers return `204 No Content` when a file is overwritten. It complies with the specification for the `PUT` verb.

204 is a successful response code and `No Content` in this case means that there is no additional content  to send in the response - https://httpstatuses.com/204

**Comment by EHekkert** [comment]
Sorry I just came across the GitHub notification mail when cleaning up my mailbox.
Thank you for clarifying.
