### ISSUE TITLE
Propfind not allowing empty path

### ISSUE THREAD

**Issue by Derpalus** [skazantsev/WebDavClient#37]
Running Propfind with an empty path throws an exception. However, this should be allowed as the BaseAddress may contain a URI that is entirely valid without having to add anything to it.

This is easily circumvented by creating your own empty Uri and giving it to Propfind, but still.

**Comment by skazantsev** [comment]
Yes, you're totally right, thanks for raising this issue.
It actually applies to all methods.

Seems like it can be fixed at this line:
https://github.com/skazantsev/WebDavClient/blob/master/src/WebDav.Client/WebDavClient.cs#L803

I can accept a Pull Request if you have time to fix it, or I can fix it myself.
Let me know what you prefer.

**Comment by Derpalus** [comment]
I'm using this via NuGet, I don't have it checked out or anything, so it's a bit of work for me to fix it, so if you could do it that would be great.

**Comment by skazantsev** [comment]
Hi @Derpalus ,
I published a new version of the library with a fix to NuGet: https://www.nuget.org/packages/WebDav.Client/2.3.1

**Comment by Derpalus** [comment]
Thanks for the speedy fix, it's great to use libraries with active developers :)
I'll update my project to use the latest version.
