### ISSUE TITLE
Only "200 - OK" results on Xamarin

### ISSUE THREAD

**Issue by tipa** [skazantsev/WebDavClient#39]
NuGet version: 2.3.1
I am having a weird issue using this library in my Xamarin.Android & Xamarin.iOS project. I am connecting with a Nextcloud 15.0.2.0. I am providing correct URL, username but WRONG password.
Now, on iOS & Android I get only "OK" responses however, no matter what methods I call, e.g.:
`PROPFIND WebDAV response - StatusCode: 200, Description: OK`

In my UWP project, I am getting the expected result:
`PROPFIND WebDAV response - StatusCode: 401, Description: Unauthorized`

Tried to debug with Fiddler, but for some reason the web traffic didn't show up.

**Comment by tipa** [comment]
Also happens when using a wrong URL, e.g. "https://xyz.com/remote.php/wevdav/" instead of "https://xyz.com/remote.php/webdav/"

**Comment by skazantsev** [comment]
Hi @tipa,
The status code comes directly from the underlying http client, so assume this is a response that is returned by the server.
I think you're on the right track with trying to capture the actual HTTP traffic.
I don't know how you actually configure your fiddler, I usually just run it locally and pass a `WebProxy` to the `WebDavClient` instance like this:
``` csharp
new WebDavClient(
    new WebDavClientParams
    {
        BaseAddress = new Uri("<URL>"),
        Proxy = new WebProxy("127.0.0.1:8888", false)
    }
)
```

I hope this helps.

**Comment by tipa** [comment]
Thanks for that small snippet. Interestingly, after using the proxy and removing that line again, the 401-Unauthorized is being returned correctly...
