### ISSUE TITLE
Please upload a strong named version to NuGet

### ISSUE THREAD

**Issue by viciousviper** [skazantsev/WebDavClient#4]
Thanks for creating this well-designed WebDAV client library. I've used it to good effect and so far without any problems whatsoever.

For the strong named version of one of my NuGet packages I need to reference WebDavClient as a signed assembly. I'd much prefer to reference a NuGet package of WebDavClient signed by its author to including a re-signed version of the library in my own packages.

**Comment by skazantsev** [comment]
Thanks for your feedback. Good point about signing. I will upload the signed version soon.

**Comment by skazantsev** [comment]
@viciousviper Starting from version 1.0.4 assembly is signed. A new version is available in nuget.
