### ISSUE TITLE
create files

### ISSUE THREAD

**Issue by braya2015** [skazantsev/WebDavClient#40]
How do I create a file in a directory in asp.net core

**Comment by skazantsev** [comment]
Hi @braya2015 ,
Could you explain the context of your problem, please?
Are you trying to use WebDavClient in an Asp.Net Core application to make a call to a WebDAV server or is it some other use-case?
Could you also share what you have tried so far?

**Comment by braya2015** [comment]
My web application in asp.net core generates a pdf file, but I need to save it in a folder already created in Nextcloud using client.Mkcol ("FilesPdf"). But the File.OpenRead function does not work in asp.net core.

client.PutFile ("file.xml", File.OpenRead ("file.xml")); // upload a resource

**Comment by skazantsev** [comment]
If an account that runs your Asp.Net Core process has necessary permissions it should be possible to read/write files.
If `File.OpenRead` fails for some reason then the exception usually gives a hint what went wrong.
