### ISSUE TITLE
PutFile of ~700MB file leads to "The I/O operation has been aborted because of either a thread exit or an application request".

### ISSUE THREAD

**Issue by eddieparker** [skazantsev/WebDavClient#41]
As full disclosure: I'm using dotnetcore and the 3.0 preview 6; so this might not be an issue with this library per se.

I'm trying to upload a large file to the webdav but I get hit with an exception:

Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..

The application certainly isn't requesting a cancel; at least not from my code.  And this works for smaller files, as well as the webdav client I've written in Python.

**Comment by skazantsev** [comment]
Hi @eddieparker,

I tried to reproduce the issue by installing dotnet core 3.0 preview 6 and uploading a large file (1GB) using the latest version of the library to a local WebDAV server and I was not able to reproduce it.

I wonder if it can be related to an issue in the .NET Core repository - 
https://github.com/dotnet/corefx/issues/30691

Here's a code sample that I have used:
``` csharp
using (var client = new WebDavClient(
    new WebDavClientParams
    {
        BaseAddress = new Uri("..."),
        Credentials = new NetworkCredential("...", "...")
    }))
{
    var response = await client.PutFile("large_file.txt", File.OpenRead(@"c:\temp\large_file.txt"), "text/plain");
    Console.WriteLine($"{response.StatusCode} - {response.Description}");
}
```
