### ISSUE TITLE
Visual Studio Tools for Office Interoperability

### ISSUE THREAD

**Issue by JulioCCosta** [skazantsev/WebDavClient#42]
I'm doing a vsto and it calls the IWebdavClient certainly because of interoperability, does this lib support this?

**Comment by skazantsev** [comment]
Hi @JulioCCosta,

From what I understand, you're asking if the library can be used in MS Office extensions developed using VSTO, is this correct?

I haven't worked with VSTO, so I may misunderstand something but seems like VSTO projects can target any version of the full .Net Framework. So, as long as your VSTO project targets .NET 4.5+ you can use WebDavClient.

I hope this answers your question and if not feel free to provide more details about the issue.
