### ISSUE TITLE
Support custom request methods

### ISSUE THREAD

**Issue by markatk** [skazantsev/WebDavClient#43]
I wanted to use this library to implement a CalDAV (which is based on WebDAV) library, but CalDAV requires a REPORT request which is not supported by this. If there was a way to send custom requests I could use this good library instead of using my own (small) implementation of WebDAV.

**Comment by skazantsev** [comment]
Unfortunately, I don't have plans to support CalDAV and I guess it's easier to use other wrapper / HttpClient for custom requests.
BTW, nice lib https://github.com/markatk/CalDAV.NET, I am glad it is sorted out.
