### ISSUE TITLE
Supporint TLS1.2 & behalf the .NET 4.6.2

### ISSUE THREAD

**Issue by maharrabi** [skazantsev/WebDavClient#48]
Hi, 
I'm actually facing some issues while using the API to connect to a webdav with TLS1.2
Question: Is the TLS1.2 supported by the HTTPClient ?

**Comment by skazantsev** [comment]
Hi @maharrabi,

Please refer to this answer - https://stackoverflow.com/a/33091871.

Looks like it's enough to set a SecurityProtocol property  (once per lifetime of your app) in order to instruct `HttpClient` to use TLS1.2 by default.
``` csharp
using System.Net;
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;
```
