### ISSUE TITLE
WebDav Service Unavailable with .net core 3.1

### ISSUE THREAD

**Issue by Glorfinkel** [skazantsev/WebDavClient#49]
Hello, 
i'm using your library with an asp.net core 2.2 api. Everything works fine.
now i tried to push the version to .net core 3.1. 
Building and running is fine, but the application is not able to connect to the webdav-server. 
It says the server would be unavailable (Http Status Code 503)

Do somebody know how to handle this issue? Is there a breaking Change in Http Requests maybe i didnt get?

Greetings,
Glorfinkel

**Comment by skazantsev** [comment]
Hi @Glorfinkel ,

I cannot reproduce the issue on .net core 3.0 and 3.1 and I'm not aware about changes in HttpClient that may affect that.

I'd recommend using a tool like [Fiddler](https://www.telerik.com/fiddler) to capture HTTP/HTTPS traffic between the application and the WebDAV server and see what request is sent.

Regards,
Sergey
