### ISSUE TITLE
Support special characters in file and directory names

### ISSUE THREAD

**Issue by viciousviper** [skazantsev/WebDavClient#5]
Trying to create a file named "Córdoba" in a directory named "España" will result in mangled (i.e. URL-encoded) file and directory names.

Please support the full range of applicable UTF 8 characters by transparently URL-decoding the file and directory names returned from API methods.

**Comment by skazantsev** [comment]
@viciousviper  If I understood you correctly you're talking about responses returned by PROPFIND.

For resources containing non-ASCII characters WebDAV servers usually return percent encoded URIs.

For example:
```
<?xml version="1.0" encoding="utf-8"?>
<D:multistatus xmlns:D="DAV:">
	<D:response>
		<D:href>http://my.webdav/Espa%C3%B1a/</D:href>
		...
	<D:response>
</D:multistatus>
```
WebDavClient returns URIs as is ensuring that the WebDAV server correctly handle them in subsequent requests.
I believe it also facilitates better integration with different WebDAV servers out there that may return non-encoded URIs.

You can handle these URIs correctly in application code by using System.Uri.

Are there any strong reasons to change the existing behavior?

Regards,
Sergey
