### ISSUE TITLE
Change ContentType of Request

### ISSUE THREAD

**Issue by samirelassal** [skazantsev/WebDavClient#56]
https://github.com/skazantsev/WebDavClient/blob/b1886fea6b44e62f1737eb688cdead8bc28c2016/src/WebDav.Client/WebDavClient.cs#L110

It would be nice if the ContentType of the RequestParameters-object could be changed from outside WebDavClient class. By default, it is set to "text/plain; charset=utf-8". For example, right now I would like it to be "application/xml; charset=utf-8".

**Comment by skazantsev** [comment]
Hi @samirelassal ,

I think it is a nice change to allow clients to set a media type for methods that have a request body.

Also `application/xml` seems to be a better default than `text/plain`.

I'd like to make the following changes:
- make `application/xml` a default media type for PROPFIND, PROPPATCH, LOCK methods.
- allow clients to override it by setting ContentType on the params object.

I will try to publish a version with these changes today.

Thanks for bringing this up!

**Comment by skazantsev** [comment]
The version 2.7.0 is released in NuGet.

**Comment by samirelassal** [comment]
Thanks a lot mate!
