### ISSUE TITLE
Problem, when using Copy & Move operations for files with whilespaces

### ISSUE THREAD

**Issue by maharrabi** [skazantsev/WebDavClient#6]
It seems that the GetAbsolutePath & CreateUri methods do not encode the urls, such as using "%20" for whitespace and so on...

To reproduce the issue, just use Copy or Move method with file(s) that contain whitespaces in filename.
exp : 
Move([AbsolutePath] + File 1.txt, [AbsolutePath2] + File 1.txt)
Or : 
Move([AbsolutePath] + File%201.txt, [AbsolutePath2] + File%201.txt)

Getting same result.

**Comment by maharrabi** [comment]
Please consider using for example : 

private string GetAbsoluteUriAsString(Uri uri)
 {
      return Uri.EscapeUriString(GetAbsoluteUri(uri).ToString());
}

in order to encode the URI.

**Comment by skazantsev** [comment]
@maharrabi thank you for bringing this up, it's a bug.
I will release a fix soon.

**Comment by skazantsev** [comment]
@maharrabi I have decided not to encode a destination URI inside COPY / MOVE methods. Instead I am now passing the _AbsoluteUri_ property of _System.Uri_. It will correctly encode spaces and if you need to support other characters that require encoding you can always encode a URI before passing it to COPY / MOVE methods.
A new version on WebDav.Client has been published to NuGet.
