### ISSUE TITLE
How to download a file?

### ISSUE THREAD

**Issue by madsholme** [skazantsev/WebDavClient#64]
I dont see any way to download the file. I can see a way to upload the file with the client.put, but how would you download the file? would you need to use GetRawFile, and then write it from that or?

Is it possible to get an example on how to do that?

**Comment by skazantsev** [comment]
@madsholme you can use `GetFile` `GetRawFile` methods.
An example can be found [here](https://github.com/skazantsev/WebDavClient/blob/main/src/WebDav.ClientConsole/Program.cs#L37).

Good luck!

**Comment by madsholme** [comment]
@skazantsev Thank you!
